# This is a config for E2B sandbox template.
# You can use template ID (ox09253pjrdb7hbhpkzb) or template name (vibe-nextjs-run-1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-run-1") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-run-1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-run-1')

team_id = "7a387491-882e-4e27-b1b5-ae080537b91e"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-run-1"
template_id = "ox09253pjrdb7hbhpkzb"
